In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import datetime as dt

In [2]:
sheets = pd.read_excel(
    r'\Data Science\_Projects\Doing\Employee Performance Analysis\Employee Performance Dataset_C30_English.xlsx',
    sheet_name=None
    )

In [3]:
sheets.keys()

dict_keys(['employees', 'stores', 'monthly_performance', 'role_kpis', 'business_outcomes', 'Data_Dictionary'])

## Employee Table

In [4]:
Employees = sheets['employees']

In [5]:
Employees.head(5)

,Employee_Id,Full_Name,Age,Education_Level,Hire_Date,Exit_Date,Department,Job_Role,Job_Level,Employment_Type,Base_Salary_Annual,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Store_Id,Manager_Id,Manager_Name,Manager_Status
0,EMP000001,Marie Kim DDS,23,Master's,26/04/2021,13/04/2022,Store Operations,Cashier,Entry,Full-time,25745.40,Charlotte,35.2271,-80.8431,STR058,EMP001131,Michelle Walls,Executive
1,EMP000002,Danny Morgan,26,Master's,03/09/2021,NaN,Store Operations,Sales Associate,Associate,Full-time,39408.57,San Jose,37.3382,-121.8863,STR137,EMP002456,Jennifer Moore,Executive
2,EMP000003,Crystal Robinson,38,Bachelor's,25/08/2016,NaN,Store Operations,Cashier,Entry,Full-time,29319.94,Jacksonville,30.3322,-81.6557,STR008,EMP000529,Melissa Bishop,Senior Manager
3,EMP000004,Mark Perez,33,Bachelor's,10/12/2021,NaN,Store Operations,Senior Sales Associate,Senior_Associate,Full-time,43979.88,Las Vegas,36.1699,-115.1398,STR063,EMP001305,Tina Walter,Senior Manager
4,EMP000005,Shannon Jones,24,High School,24/02/2018,NaN,Store Operations,Cashier,Entry,Full-time,23560.19,Chicago,41.8781,-87.6298,STR109,EMP001823,Nicholas Fitzgerald,Senior Manager

In [6]:
Employees.columns

Index(['Employee_Id', 'Full_Name', 'Age', 'Education_Level', 'Hire_Date',
       'Exit_Date', 'Department', 'Job_Role', 'Job_Level', 'Employment_Type',
       'Base_Salary_Annual', 'Store_Location', 'Store_Location_Latitude',
       'Store_Location_Longitude', 'Store_Id', 'Manager_Id', 'Manager_Name',
       'Manager_Status'],
      dtype='object')

In [7]:
Employees.isnull().sum()

Employee_Id                    0
Full_Name                      0
Age                            0
Education_Level                0
Hire_Date                      0
Exit_Date                   6009
Department                     0
Job_Role                       0
Job_Level                      0
Employment_Type                0
Base_Salary_Annual             0
Store_Location                 0
Store_Location_Latitude        0
Store_Location_Longitude       0
Store_Id                       0
Manager_Id                     5
Manager_Name                   5
Manager_Status                 5
dtype: int64

In [8]:
len(Employees['Store_Id'].unique())

150

In [9]:
Employees.shape

(7500, 18)

In [10]:
Employees.columns

Index(['Employee_Id', 'Full_Name', 'Age', 'Education_Level', 'Hire_Date',
       'Exit_Date', 'Department', 'Job_Role', 'Job_Level', 'Employment_Type',
       'Base_Salary_Annual', 'Store_Location', 'Store_Location_Latitude',
       'Store_Location_Longitude', 'Store_Id', 'Manager_Id', 'Manager_Name',
       'Manager_Status'],
      dtype='object')

In [11]:
for col in Employees.columns:
    if Employees[col].is_unique:
        print(f"{col} :=====>> Unique")

Employee_Id :=====>> Unique

In [12]:
Employees['Employee_Id'].nunique()

7500

In [13]:
Employees.describe()

,Age,Base_Salary_Annual,Store_Location_Latitude,Store_Location_Longitude
count,7500.000000,7500.000000,7500.000000,7500.000000
mean,32.450000,27253.855732,36.954572,-96.160918
std,7.482319,10217.242704,4.878566,16.457037
min,21.000000,8823.460000,29.424100,-122.678400
25%,27.000000,19899.520000,32.776700,-112.074000
50%,32.000000,27394.165000,36.169900,-95.369800
75%,37.000000,31945.697500,39.961200,-82.998800
max,64.000000,177873.610000,47.606200,-71.058900

In [14]:
Employees.dtypes

Employee_Id                  object
Full_Name                    object
Age                           int64
Education_Level              object
Hire_Date                    object
Exit_Date                    object
Department                   object
Job_Role                     object
Job_Level                    object
Employment_Type              object
Base_Salary_Annual          float64
Store_Location               object
Store_Location_Latitude     float64
Store_Location_Longitude    float64
Store_Id                     object
Manager_Id                   object
Manager_Name                 object
Manager_Status               object
dtype: object

In [15]:
Employees['Hire_Date'] = pd.to_datetime(Employees['Hire_Date'], format='%d/%m/%Y')
Employees['Exit_Date'] = pd.to_datetime(Employees['Exit_Date'], format='%d/%m/%Y')

In [16]:
Employees[['Hire_Date', 'Exit_Date']]

      Hire_Date  Exit_Date
0    2021-04-26 2022-04-13
1    2021-09-03        NaT
2    2016-08-25        NaT
3    2021-12-10        NaT
4    2018-02-24        NaT
...         ...        ...
7495 2020-01-01        NaT
7496 2016-04-11        NaT
7497 2020-07-23        NaT
7498 2021-07-28 2023-02-15
7499 2019-10-09        NaT

[7500 rows x 2 columns]

In [17]:
len(Employees[Employees['Exit_Date'].isna()])

6009

In [18]:
Employees.dtypes

Employee_Id                         object
Full_Name                           object
Age                                  int64
Education_Level                     object
Hire_Date                   datetime64[ns]
Exit_Date                   datetime64[ns]
Department                          object
Job_Role                            object
Job_Level                           object
Employment_Type                     object
Base_Salary_Annual                 float64
Store_Location                      object
Store_Location_Latitude            float64
Store_Location_Longitude           float64
Store_Id                            object
Manager_Id                          object
Manager_Name                        object
Manager_Status                      object
dtype: object

In [19]:
Employees['Hire_Date'].dt.date

0       2021-04-26
1       2021-09-03
2       2016-08-25
3       2021-12-10
4       2018-02-24
           ...
7495    2020-01-01
7496    2016-04-11
7497    2020-07-23
7498    2021-07-28
7499    2019-10-09
Name: Hire_Date, Length: 7500, dtype: object

In [20]:
Employees['Exit_Date'].dt.date

0       2022-04-13
1              NaT
2              NaT
3              NaT
4              NaT
           ...
7495           NaT
7496           NaT
7497           NaT
7498    2023-02-15
7499           NaT
Name: Exit_Date, Length: 7500, dtype: object

In [21]:
print(f"Total Employees still working {Employees['Exit_Date'].isnull().sum()} employees.")

Total Employees still working 6009 employees.

In [22]:
emp_cols = Employees.columns

In [23]:
emp_cols

Index(['Employee_Id', 'Full_Name', 'Age', 'Education_Level', 'Hire_Date',
       'Exit_Date', 'Department', 'Job_Role', 'Job_Level', 'Employment_Type',
       'Base_Salary_Annual', 'Store_Location', 'Store_Location_Latitude',
       'Store_Location_Longitude', 'Store_Id', 'Manager_Id', 'Manager_Name',
       'Manager_Status'],
      dtype='object')

In [24]:
Employees.groupby(['Employment_Type', 'Job_Level'])['Base_Salary_Annual'].agg(['mean', 'min', 'max'])

                                           mean        min        max
Employment_Type Job_Level
Contractor      Associate          36649.410204   30819.45   43801.86
                Entry              29284.262025   24278.01   35153.08
                Manager            72128.370000   72128.37   72128.37
                Senior_Associate   47858.950769   39627.83   54174.36
                Supervisor         55438.436667   48974.24   65988.39
Full-time       Associate          33940.257140   28004.82   39993.53
                Entry              27030.933609   22000.12   31993.50
                Executive         165662.595000  153451.58  177873.61
                Manager            70360.075417   57304.09   83571.60
                Senior_Associate   42242.676839   35137.48   49988.11
                Senior_Manager     99512.603077   82051.75  116453.67
                Supervisor         50953.853529   42078.54   59921.36
Part-time       Associate          20210.206759   16801.74   23988.10
                Entry              16246.849899   13203.59   19198.31
                Executive          87828.485000   78681.44   96975.53
                Manager            43598.597500   39027.81   46724.26
                Senior_Associate   25342.194294   21017.93   29981.41
                Senior_Manager     57098.260000   57098.26   57098.26
                Supervisor         30630.856984   25307.67   35882.55
Seasonal        Associate          13632.877600   11218.39   15994.74
                Entry              10773.593758    8823.46   12786.11
                Executive          48749.850000   48749.85   48749.85
                Manager            25638.500000   25638.50   25638.50
                Senior_Associate   16505.393860   14061.71   19739.69
                Senior_Manager     34194.380000   34194.38   34194.38
                Supervisor         20448.887333   16910.84   23694.90

In [25]:
emp_cols

Index(['Employee_Id', 'Full_Name', 'Age', 'Education_Level', 'Hire_Date',
       'Exit_Date', 'Department', 'Job_Role', 'Job_Level', 'Employment_Type',
       'Base_Salary_Annual', 'Store_Location', 'Store_Location_Latitude',
       'Store_Location_Longitude', 'Store_Id', 'Manager_Id', 'Manager_Name',
       'Manager_Status'],
      dtype='object')

In [26]:
Employees['Manager_Status'].value_counts()

Manager_Status
Manager           4478
Senior Manager    2248
Executive          769
Name: count, dtype: int64

In [27]:
Employees.groupby(['Department'])['Base_Salary_Annual'].agg(['mean', 'min', 'max'])

                               mean       min        max
Department
Customer Service       26244.393800   9449.99   50949.01
Finance                28055.533689   8987.86  101294.41
Fresh Produce          26915.946969   8998.42  110475.60
HR                     26539.921733   8823.46   58951.29
IT                     28560.182889  10544.19  115178.51
Logistics/Warehousing  27574.698600   9027.53  153451.58
Marketing              26796.816800   9736.23   65923.63
Meat/Fish & Bakery     26535.722133   8867.88  116453.67
Store Operations       27404.359873   8848.62  177873.61

In [28]:
Employees['Base_Salary_Monthly'] = Employees['Base_Salary_Annual'] / 12

In [29]:
Employees[['Base_Salary_Annual', 'Base_Salary_Monthly']]

      Base_Salary_Annual  Base_Salary_Monthly
0               25745.40          2145.450000
1               39408.57          3284.047500
2               29319.94          2443.328333
3               43979.88          3664.990000
4               23560.19          1963.349167
...                  ...                  ...
7495            28940.06          2411.671667
7496            22725.75          1893.812500
7497            34383.43          2865.285833
7498            15277.10          1273.091667
7499            28687.53          2390.627500

[7500 rows x 2 columns]

In [30]:
Employees['Manager_Id'].unique()

array(['EMP001131', 'EMP002456', 'EMP000529', 'EMP001305', 'EMP001823',
       'EMP002436', 'EMP002585', 'EMP002684', 'EMP002712', 'EMP000053',
       'EMP000121', 'EMP000240', 'EMP000520', 'EMP000767', 'EMP001026',
       'EMP001224', 'EMP001447', 'EMP001680', 'EMP002163', 'EMP002493',
       'EMP002827', nan, 'EMP003940', 'EMP003098', 'EMP003215',
       'EMP003552', 'EMP003994', 'EMP003554', 'EMP003586', 'EMP003693',
       'EMP003781', 'EMP003856', 'EMP003891', 'EMP003892', 'EMP004184',
       'EMP005303', 'EMP004636', 'EMP004669', 'EMP004809', 'EMP005337',
       'EMP006822', 'EMP007274', 'EMP006232', 'EMP006865', 'EMP007124',
       'EMP005849', 'EMP006342', 'EMP006675', 'EMP006762', 'EMP006986',
       'EMP007299'], dtype=object)

In [31]:
len(Employees['Manager_Id'].unique())

51

In [32]:
Total_managers = Employees['Manager_Id'].nunique()
print(Total_managers)

50

In [33]:
exitDate = ~Employees['Exit_Date'].isna()
exit_emp = Employees[exitDate]

In [34]:
exit_emp.head()

,Employee_Id,Full_Name,Age,Education_Level,Hire_Date,Exit_Date,Department,Job_Role,Job_Level,Employment_Type,Base_Salary_Annual,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Store_Id,Manager_Id,Manager_Name,Manager_Status,Base_Salary_Monthly
0,EMP000001,Marie Kim DDS,23,Master's,2021-04-26,2022-04-13,Store Operations,Cashier,Entry,Full-time,25745.40,Charlotte,35.2271,-80.8431,STR058,EMP001131,Michelle Walls,Executive,2145.450000
7,EMP000008,Richard Aguirre,27,High School,2019-01-26,2021-04-04,Store Operations,Cashier,Entry,Full-time,30661.76,Phoenix,33.4484,-112.0740,STR144,EMP002684,David James,Senior Manager,2555.146667
8,EMP000009,Brent Jordan,36,Some College,2021-01-26,2024-10-02,Store Operations,Sales Associate,Associate,Full-time,35213.38,New York,40.7128,-74.0060,STR034,EMP002712,Scott Meza,Senior Manager,2934.448333
22,EMP000023,Brittney Phillips,29,Some College,2021-10-03,2024-12-02,Store Operations,Cashier,Entry,Full-time,24921.45,Las Vegas,36.1699,-115.1398,STR060,EMP001131,Michelle Walls,Executive,2076.787500
25,EMP000026,Sarah Moore,48,Master's,2018-12-21,2019-04-18,Store Operations,Cashier,Entry,Part-time,17911.06,Detroit,42.3314,-83.0458,STR098,EMP001305,Tina Walter,Senior Manager,1492.588333

In [35]:
exit_emp.isna().sum()

Employee_Id                 0
Full_Name                   0
Age                         0
Education_Level             0
Hire_Date                   0
Exit_Date                   0
Department                  0
Job_Role                    0
Job_Level                   0
Employment_Type             0
Base_Salary_Annual          0
Store_Location              0
Store_Location_Latitude     0
Store_Location_Longitude    0
Store_Id                    0
Manager_Id                  0
Manager_Name                0
Manager_Status              0
Base_Salary_Monthly         0
dtype: int64

In [36]:
Total_Existed_Employees = len(exit_emp)
print(f"Total Exit Employees = {Total_Existed_Employees}")

Total Exit Employees = 1491

In [106]:
bins = [20, 31, 42, 53, 65]
labels = ["21-31", "32-42", "43-53", "54-64"]

In [107]:
Employees['Age Group'] = pd.cut(Employees['Age'], bins=bins, labels=labels)

## Store Table

In [39]:
stores = sheets['stores']

In [40]:
stores.head()

,Store_Id,Store_Name,City,City_Latitude,City_Longitude,Store_Type,Opening_Date
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
1,STR002,Charlotte Regular #2,Charlotte,35.2271,-80.8431,Regular,09/11/2015
2,STR003,Portland Superstore #3,Portland,45.5152,-122.6784,Superstore,08/02/2018
3,STR004,Nashville Superstore #4,Nashville,36.1627,-86.7816,Superstore,21/08/2017
4,STR005,Austin Regular #5,Austin,30.2672,-97.7431,Regular,04/04/2022

In [41]:
stores.shape

(150, 7)

In [42]:
new_stores = stores.join(Employees.set_index('Store_Id'), on='Store_Id', how='left')

In [43]:
new_stores.head()

,Store_Id,Store_Name,City,City_Latitude,City_Longitude,Store_Type,Opening_Date,Employee_Id,Full_Name,Age,...,Employment_Type,Base_Salary_Annual,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Manager_Id,Manager_Name,Manager_Status,Base_Salary_Monthly,Age Group
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021,EMP000020,William Baker,42,...,Full-time,24912.29,Louisville,38.2527,-85.7585,EMP002163,Mr. William Ward,Manager,2076.024167,32-42
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021,EMP000022,Whitney Peters,29,...,Full-time,29673.93,Seattle,47.6062,-122.3321,EMP002827,Amanda Wright,Manager,2472.827500,21-31
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021,EMP000378,Emily Bennett,29,...,Full-time,22232.72,Fort Worth,32.7555,-97.3308,EMP001447,Sonya Jackson,Manager,1852.726667,21-31
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021,EMP000751,Jim Newton,23,...,Part-time,17641.67,Nashville,36.1627,-86.7816,EMP000053,Rebecca Valencia,Manager,1470.139167,21-31
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021,EMP000796,Breanna Ayala,38,...,Full-time,30721.24,Jacksonville,30.3322,-81.6557,EMP000240,Briana Murray,Manager,2560.103333,32-42

In [44]:
new_stores.isna().sum()

Store_Id                       0
Store_Name                     0
City                           0
City_Latitude                  0
City_Longitude                 0
Store_Type                     0
Opening_Date                   0
Employee_Id                    0
Full_Name                      0
Age                            0
Education_Level                0
Hire_Date                      0
Exit_Date                   6009
Department                     0
Job_Role                       0
Job_Level                      0
Employment_Type                0
Base_Salary_Annual             0
Store_Location                 0
Store_Location_Latitude        0
Store_Location_Longitude       0
Manager_Id                     5
Manager_Name                   5
Manager_Status                 5
Base_Salary_Monthly            0
Age Group                      0
dtype: int64

In [45]:
stores.columns

Index(['Store_Id', 'Store_Name', 'City', 'City_Latitude', 'City_Longitude',
       'Store_Type', 'Opening_Date'],
      dtype='object')

In [46]:
new_stores.columns

Index(['Store_Id', 'Store_Name', 'City', 'City_Latitude', 'City_Longitude',
       'Store_Type', 'Opening_Date', 'Employee_Id', 'Full_Name', 'Age',
       'Education_Level', 'Hire_Date', 'Exit_Date', 'Department', 'Job_Role',
       'Job_Level', 'Employment_Type', 'Base_Salary_Annual', 'Store_Location',
       'Store_Location_Latitude', 'Store_Location_Longitude', 'Manager_Id',
       'Manager_Name', 'Manager_Status', 'Base_Salary_Monthly', 'Age Group'],
      dtype='object')

In [47]:
new_stores['Store_Type'].value_counts()

Store_Type
Regular       4067
Superstore    2463
Express        970
Name: count, dtype: int64

In [48]:
new_stores.groupby(['Store_Name'])['Employee_Id'].count().sort_values(ascending=False)

Store_Name
Las Vegas Regular #69          68
San Jose Superstore #112       67
Los Angeles Regular #23        66
Dallas Regular #80             64
Jacksonville Superstore #82    63
                               ..
Portland Superstore #3         39
Louisville Superstore #71      36
Memphis Regular #53            35
Houston Superstore #104        32
Seattle Superstore #144        31
Name: Employee_Id, Length: 150, dtype: int64

In [49]:
#### It counts nans in employee_Id
# print('   Top 10 stores that have employees')
# new_stores.groupby('Store_Name') \
#           .size() \
#           .reset_index(name='employee_count') \
#           .sort_values('employee_count', ascending=False)[:10]

## Top 10 Stores by Employees

In [50]:
new_stores.groupby('Store_Name') \
          .agg(employee_count=('Employee_Id', 'count')) \
          .sort_values('employee_count', ascending=False).head(10)

                             employee_count
Store_Name
Las Vegas Regular #69                    68
San Jose Superstore #112                 67
Los Angeles Regular #23                  66
Dallas Regular #80                       64
Jacksonville Superstore #82              63
Baltimore Regular #106                   62
Chicago Regular #145                     62
Chicago Regular #105                     62
Portland Superstore #133                 61
Charlotte Regular #66                    60

In [51]:
cols = list(stores.columns)
new_stores = new_stores[cols]

In [52]:
new_stores.columns

Index(['Store_Id', 'Store_Name', 'City', 'City_Latitude', 'City_Longitude',
       'Store_Type', 'Opening_Date'],
      dtype='object')

In [53]:
new_stores.isna().sum()

Store_Id          0
Store_Name        0
City              0
City_Latitude     0
City_Longitude    0
Store_Type        0
Opening_Date      0
dtype: int64

In [54]:
new_stores['Store_Id'].nunique()

150

In [55]:
new_stores.shape

(7500, 7)

In [56]:
new_stores['Store_Id'].shape

(7500,)

In [57]:
print(new_stores[cols].duplicated().sum())

7350

In [58]:
new_stores[new_stores.duplicated()].head()

,Store_Id,Store_Name,City,City_Latitude,City_Longitude,Store_Type,Opening_Date
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021

In [59]:
new_stores = new_stores.drop_duplicates(subset=['Store_Id'])

In [60]:
new_stores.head()

,Store_Id,Store_Name,City,City_Latitude,City_Longitude,Store_Type,Opening_Date
0,STR001,San Antonio Regular #1,San Antonio,29.4241,-98.4936,Regular,20/05/2021
1,STR002,Charlotte Regular #2,Charlotte,35.2271,-80.8431,Regular,09/11/2015
2,STR003,Portland Superstore #3,Portland,45.5152,-122.6784,Superstore,08/02/2018
3,STR004,Nashville Superstore #4,Nashville,36.1627,-86.7816,Superstore,21/08/2017
4,STR005,Austin Regular #5,Austin,30.2672,-97.7431,Regular,04/04/2022

In [61]:
new_stores.shape

(150, 7)

In [62]:
new_stores.dtypes

Store_Id           object
Store_Name         object
City               object
City_Latitude     float64
City_Longitude    float64
Store_Type         object
Opening_Date       object
dtype: object

In [63]:
Stores = new_stores

In [64]:
Stores['Opening_Date'] = pd.to_datetime(Stores['Opening_Date'], format="%d/%m/%Y")

In [65]:
Stores.dtypes

Store_Id                  object
Store_Name                object
City                      object
City_Latitude            float64
City_Longitude           float64
Store_Type                object
Opening_Date      datetime64[ns]
dtype: object

In [66]:
Stores.isna().sum()

Store_Id          0
Store_Name        0
City              0
City_Latitude     0
City_Longitude    0
Store_Type        0
Opening_Date      0
dtype: int64

In [67]:
Stores['Store_Type'].value_counts()

Store_Type
Regular       80
Superstore    51
Express       19
Name: count, dtype: int64

In [68]:
sheets.keys()

dict_keys(['employees', 'stores', 'monthly_performance', 'role_kpis', 'business_outcomes', 'Data_Dictionary'])

In [69]:
Monthly_performance = sheets['monthly_performance']

In [70]:
Monthly_performance.head()

,Employee_Id,Year_Month,Performance_Rating,Training_Hours,Overtime_Hours,Absenteeism_Days,Promotion_Flag,Salary_Increase_Flag,Monthly_Bonus,Benefits_Cost,Employee_Satisfaction,Engagement_Index,Manager_Evaluation
0,EMP000001,2022-01,4.13,2,15,1,False,False,657.44,1727.09,8.0,8.1,4.5
1,EMP000002,2022-01,3.60,9,10,1,False,False,626.76,1584.89,8.0,9.1,3.6
2,EMP000003,2022-01,3.65,3,12,0,False,False,554.12,1584.56,6.3,5.1,3.5
3,EMP000004,2022-01,3.51,6,8,0,False,False,669.14,1759.48,8.1,8.0,3.3
4,EMP000005,2022-01,5.00,1,4,1,False,False,235.22,947.89,10.0,9.7,5.0

In [71]:
Monthly_performance.duplicated().sum()

np.int64(0)

In [72]:
Monthly_performance['Year_Performance'] = Monthly_performance['Year_Month'].astype('str').str[:4]

In [73]:
Monthly_performance['Year_Performance']

0         2022
1         2022
2         2022
3         2022
4         2022
          ...
236586    2024
236587    2024
236588    2024
236589    2024
236590    2024
Name: Year_Performance, Length: 236591, dtype: object

In [74]:
Monthly_performance = Monthly_performance.rename(columns={'Year_Performance' : 'Year'})

In [75]:
Monthly_performance['Year']

0         2022
1         2022
2         2022
3         2022
4         2022
          ...
236586    2024
236587    2024
236588    2024
236589    2024
236590    2024
Name: Year, Length: 236591, dtype: object

## Top 10 Employees performance Per Year

In [76]:
print('Top 10 Employees performance Per Year')
Monthly_performance.groupby(['Employee_Id', 'Year'])\
    .agg(
        Total_Preformance=('Performance_Rating', 'sum'),
        Average_Performance=('Performance_Rating', 'mean'),
        Minimum_Performance = ('Performance_Rating', 'min'), 
        Maximum_Performance = ('Performance_Rating', 'max'),
        Months_Active=('Performance_Rating', 'count'))\
        .sort_values('Total_Preformance', ascending=False).head(10)

Top 10 Employees performance Per Year

,,Total_Preformance,Average_Performance,Minimum_Performance,Maximum_Performance,Months_Active
Employee_Id,Year,,,,,
EMP001765,2024,56.65,4.720833,4.50,5.00,12
EMP000939,2024,56.42,4.701667,4.51,4.99,12
EMP001746,2022,56.29,4.690833,4.37,5.00,12
EMP006311,2022,56.00,4.666667,4.34,4.85,12
EMP006753,2023,55.98,4.665000,4.49,5.00,12
EMP004334,2023,55.81,4.650833,4.52,4.83,12
EMP000752,2024,55.78,4.648333,4.30,5.00,12
EMP000939,2023,55.76,4.646667,4.20,5.00,12
EMP005409,2023,55.70,4.641667,4.25,4.94,12
EMP006753,2024,55.66,4.638333,4.35,4.97,12

In [77]:
Monthly_performance.head()

,Employee_Id,Year_Month,Performance_Rating,Training_Hours,Overtime_Hours,Absenteeism_Days,Promotion_Flag,Salary_Increase_Flag,Monthly_Bonus,Benefits_Cost,Employee_Satisfaction,Engagement_Index,Manager_Evaluation,Year
0,EMP000001,2022-01,4.13,2,15,1,False,False,657.44,1727.09,8.0,8.1,4.5,2022
1,EMP000002,2022-01,3.60,9,10,1,False,False,626.76,1584.89,8.0,9.1,3.6,2022
2,EMP000003,2022-01,3.65,3,12,0,False,False,554.12,1584.56,6.3,5.1,3.5,2022
3,EMP000004,2022-01,3.51,6,8,0,False,False,669.14,1759.48,8.1,8.0,3.3,2022
4,EMP000005,2022-01,5.00,1,4,1,False,False,235.22,947.89,10.0,9.7,5.0,2022

In [110]:
Employees.head(2)

,Employee_Id,Full_Name,Age,Education_Level,Hire_Date,Exit_Date,Department,Job_Role,Job_Level,Employment_Type,Base_Salary_Annual,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Store_Id,Manager_Id,Manager_Name,Manager_Status,Base_Salary_Monthly,Age Group
0,EMP000001,Marie Kim DDS,23,Master's,2021-04-26,2022-04-13,Store Operations,Cashier,Entry,Full-time,25745.40,Charlotte,35.2271,-80.8431,STR058,EMP001131,Michelle Walls,Executive,2145.4500,21-31
1,EMP000002,Danny Morgan,26,Master's,2021-09-03,NaT,Store Operations,Sales Associate,Associate,Full-time,39408.57,San Jose,37.3382,-121.8863,STR137,EMP002456,Jennifer Moore,Executive,3284.0475,21-31

In [ ]:
EmpPerformance = pd.merge(Monthly_performance, Employees, on='Employee_Id')

In [114]:
EmpPerformance.head()

,Employee_Id,Year_Month,Performance_Rating,Training_Hours,Overtime_Hours,Absenteeism_Days,Promotion_Flag,Salary_Increase_Flag,Monthly_Bonus,Benefits_Cost,...,Base_Salary_Annual,Store_Location,Store_Location_Latitude,Store_Location_Longitude,Store_Id,Manager_Id,Manager_Name,Manager_Status,Base_Salary_Monthly,Age Group
0,EMP000001,2022-01,4.13,2,15,1,False,False,657.44,1727.09,...,25745.40,Charlotte,35.2271,-80.8431,STR058,EMP001131,Michelle Walls,Executive,2145.450000,21-31
1,EMP000002,2022-01,3.60,9,10,1,False,False,626.76,1584.89,...,39408.57,San Jose,37.3382,-121.8863,STR137,EMP002456,Jennifer Moore,Executive,3284.047500,21-31
2,EMP000003,2022-01,3.65,3,12,0,False,False,554.12,1584.56,...,29319.94,Jacksonville,30.3322,-81.6557,STR008,EMP000529,Melissa Bishop,Senior Manager,2443.328333,32-42
3,EMP000004,2022-01,3.51,6,8,0,False,False,669.14,1759.48,...,43979.88,Las Vegas,36.1699,-115.1398,STR063,EMP001305,Tina Walter,Senior Manager,3664.990000,32-42
4,EMP000005,2022-01,5.00,1,4,1,False,False,235.22,947.89,...,23560.19,Chicago,41.8781,-87.6298,STR109,EMP001823,Nicholas Fitzgerald,Senior Manager,1963.349167,21-31

In [151]:
EmpPerformance.groupby(['Age Group'], observed=False).agg(
    avg_performance=("Performance_Rating", 'mean')
).sort_values('avg_performance', ascending=False)

           avg_performance
Age Group
43-53             3.722724
32-42             3.710696
21-31             3.690236
54-64             3.675449

## Top 10 Employees AVG Satisfaction Per Year

In [120]:
Monthly_performance.groupby(['Employee_Id', 'Year'])\
    .agg(
        Avg_satisfaction=('Employee_Satisfaction', 'mean'),
        Average_Performance=('Performance_Rating', 'mean'),
        Total_Absenteeism_days = ('Absenteeism_Days', 'sum'), 
        Avg_Benefits_Cost = ('Benefits_Cost', 'mean'))\
        .sort_values('Avg_satisfaction', ascending=False).head(10)

,,Avg_satisfaction,Average_Performance,Total_Absenteeism_days,Avg_Benefits_Cost
Employee_Id,Year,,,,
EMP002160,2023,9.600000,3.280000,0,56.20
EMP004720,2024,9.600000,4.350000,1,95.08
EMP006270,2024,9.500000,4.030000,1,1242.77
EMP001007,2023,9.400000,4.560000,2,1642.76
EMP002021,2024,9.250000,4.172500,4,88.11
EMP003292,2023,9.100000,4.160000,3,447.21
EMP006112,2024,9.100000,3.430000,0,58.17
EMP004547,2024,9.083333,4.631667,4,161.63
EMP005204,2022,9.000000,3.380000,0,187.80
EMP002969,2024,8.933333,4.510000,4,1638.06

In [121]:
sheets.keys()

dict_keys(['employees', 'stores', 'monthly_performance', 'role_kpis', 'business_outcomes', 'Data_Dictionary'])

In [122]:
Role_KPIs = sheets['role_kpis']

In [123]:
Role_KPIs.head()

,Employee_Id,Year_Month,Kpi_1_Value,Kpi_1_Name,Kpi_2_Value,Kpi_2_Name,Kpi_3_Value,Kpi_3_Name,Productivity_Index,Year
0,EMP000001,2022-01,87.77,Task Completion Rate %,8.20,Quality Score,9.15,Efficiency Rating,1.565,2022
1,EMP000002,2022-01,88.94,Task Completion Rate %,6.66,Quality Score,6.09,Efficiency Rating,1.302,2022
2,EMP000003,2022-01,85.00,Store Sales vs Target %,17.37,Employee Turnover %,7.21,Customer Satisfaction,1.323,2022
3,EMP000004,2022-01,88.51,Store Sales vs Target %,7.98,Employee Turnover %,8.60,Customer Satisfaction,1.253,2022
4,EMP000005,2022-01,100.00,Task Completion Rate %,8.26,Quality Score,8.82,Efficiency Rating,2.000,2022

In [124]:

def KPIs_value_Counts(kpiCol):
    return kpiCol.value_counts()

KPIs_value_Counts(Role_KPIs['Kpi_1_Name'])

Kpi_1_Name
Task Completion Rate %         150343
Store Sales vs Target %         19254
Items Scanned per Hour          18428
Stocking Speed (items/hour)      9794
On-Time Delivery %               9315
Waste Percentage                 9028
Orders Processed per Hour        8896
Production Time (min/order)      5999
Production Time (min/batch)      5534
Name: count, dtype: int64

In [125]:
KPIs_value_Counts(Role_KPIs['Kpi_2_Name'])

Kpi_2_Name
Quality Score               155877
Employee Turnover %          19254
Till Accuracy %              18428
Stock Placement Errors %      9794
Deliveries per Day            9315
Freshness Score               9028
Picking Accuracy %            8896
Hygiene Audit Score           5999
Name: count, dtype: int64

In [126]:
KPIs_value_Counts(Role_KPIs['Kpi_3_Name'])

Kpi_3_Name
Efficiency Rating        150343
Customer Satisfaction     19254
Customer Complaints       18428
Waste Percentage          11533
Shrinkage %                9794
Customer Rating            9315
Sales per Sq Ft            9028
Safety Incidents           8896
Name: count, dtype: int64

In [127]:
Role_KPIs['Year'] = Role_KPIs['Year_Month'].astype('str').str[:4]

In [128]:
Role_KPIs['Year']

0         2022
1         2022
2         2022
3         2022
4         2022
          ...
236586    2024
236587    2024
236588    2024
236589    2024
236590    2024
Name: Year, Length: 236591, dtype: object

In [129]:
Role_KPIs.columns

Index(['Employee_Id', 'Year_Month', 'Kpi_1_Value', 'Kpi_1_Name', 'Kpi_2_Value',
       'Kpi_2_Name', 'Kpi_3_Value', 'Kpi_3_Name', 'Productivity_Index',
       'Year'],
      dtype='object')

In [130]:
Role_KPIs.groupby(['Employee_Id', 'Kpi_1_Name', 'Kpi_2_Name', 'Kpi_3_Name'])\
                .agg(Avg_Productivity_Index=('Productivity_Index', 'mean'))\
                .sort_values('Avg_Productivity_Index', ascending=False).head(10)

                                                                               Avg_Productivity_Index
Employee_Id Kpi_1_Name              Kpi_2_Name          Kpi_3_Name
EMP001325   Items Scanned per Hour  Till Accuracy %     Customer Complaints                  1.945000
EMP000939   Store Sales vs Target % Employee Turnover % Customer Satisfaction                1.802000
EMP006753   Task Completion Rate %  Quality Score       Efficiency Rating                    1.779167
EMP002339   Items Scanned per Hour  Till Accuracy %     Customer Complaints                  1.776194
EMP001746   Task Completion Rate %  Quality Score       Efficiency Rating                    1.770528
EMP005747   Task Completion Rate %  Quality Score       Efficiency Rating                    1.763083
EMP002775   Items Scanned per Hour  Till Accuracy %     Customer Complaints                  1.762650
EMP005848   Task Completion Rate %  Quality Score       Efficiency Rating                    1.761361
EMP000919   Task Completion Rate %  Quality Score       Efficiency Rating                    1.757389
EMP002606   Task Completion Rate %  Quality Score       Efficiency Rating                    1.756528

In [131]:
def top_kpi_values(kpiCol):
    return Role_KPIs.groupby(kpiCol)\
        .agg(Avg_KPI_Value=(f'{kpiCol.replace("Name", "Value")}', 'mean'))\
        .sort_values('Avg_KPI_Value', ascending=False).head(15)

In [132]:
top_kpi_values('Kpi_1_Name')

                             Avg_KPI_Value
Kpi_1_Name
Items Scanned per Hour          905.761232
Stocking Speed (items/hour)     104.297424
Store Sales vs Target %          95.503886
Task Completion Rate %           86.627873
On-Time Delivery %               86.086317
Orders Processed per Hour        41.070754
Production Time (min/batch)      40.820126
Production Time (min/order)      10.905006
Waste Percentage                  3.527090

In [133]:
top_kpi_values('Kpi_2_Name')

                          Avg_KPI_Value
Kpi_2_Name
Till Accuracy %               95.573710
Picking Accuracy %            91.567264
Hygiene Audit Score           84.002522
Deliveries per Day            25.499262
Employee Turnover %           11.231229
Freshness Score                7.695591
Quality Score                  7.344749
Stock Placement Errors %       2.369447

In [134]:
top_kpi_values('Kpi_3_Name')

                       Avg_KPI_Value
Kpi_3_Name
Sales per Sq Ft           408.094406
Customer Satisfaction       7.638112
Efficiency Rating           6.858068
Customer Rating             3.906771
Waste Percentage            3.860622
Shrinkage %                 1.666170
Customer Complaints         1.486617
Safety Incidents            0.373843

In [135]:
Role_KPIs[Role_KPIs['Kpi_3_Name'] == 'Customer Rating']

,Employee_Id,Year_Month,Kpi_1_Value,Kpi_1_Name,Kpi_2_Value,Kpi_2_Name,Kpi_3_Value,Kpi_3_Name,Productivity_Index,Year
2844,EMP003005,2022-01,80.00,On-Time Delivery %,18.78,Deliveries per Day,3.52,Customer Rating,0.625,2022
2850,EMP003011,2022-01,80.00,On-Time Delivery %,22.78,Deliveries per Day,3.47,Customer Rating,0.832,2022
2851,EMP003012,2022-01,87.21,On-Time Delivery %,25.20,Deliveries per Day,4.56,Customer Rating,1.598,2022
2869,EMP003033,2022-01,95.61,On-Time Delivery %,28.10,Deliveries per Day,4.29,Customer Rating,1.674,2022
2873,EMP003038,2022-01,80.00,On-Time Delivery %,22.28,Deliveries per Day,4.30,Customer Rating,1.210,2022
...,...,...,...,...,...,...,...,...,...,...
234134,EMP004451,2024-12,100.00,On-Time Delivery %,17.45,Deliveries per Day,4.63,Customer Rating,1.739,2024
234142,EMP004459,2024-12,92.35,On-Time Delivery %,37.13,Deliveries per Day,4.08,Customer Rating,1.384,2024
234148,EMP004465,2024-12,98.28,On-Time Delivery %,33.75,Deliveries per Day,4.57,Customer Rating,1.467,2024
234167,EMP004496,2024-12,98.10,On-Time Delivery %,32.14,Deliveries per Day,4.09,Customer Rating,1.394,2024
234169,EMP004498,2024-12,91.13,On-Time Delivery %,25.26,Deliveries per Day,4.16,Customer Rating,1.188,2024

In [136]:
sheets.keys()

dict_keys(['employees', 'stores', 'monthly_performance', 'role_kpis', 'business_outcomes', 'Data_Dictionary'])

In [137]:
Business_Outcomes = sheets['business_outcomes']

In [138]:
Business_Outcomes.head()

,Store_Id,Department,Year_Month,Sales_Target,Sales_Actual,Customer_Satisfaction,Nps_Score,Waste_Percentage,On_Time_Delivery,Year
0,STR001,Store Operations,2022-01,153000,164399.59,7.4,47.0,0.73,98.6,2022
1,STR001,Fresh Produce,2022-01,38250,39851.00,8.5,51.5,2.73,92.4,2022
2,STR001,Meat/Fish & Bakery,2022-01,29750,30829.76,5.6,-24.1,3.64,92.3,2022
3,STR002,Store Operations,2022-01,153000,143176.34,6.8,14.6,1.68,87.6,2022
4,STR002,Fresh Produce,2022-01,38250,38637.44,6.1,3.3,4.43,94.3,2022

In [139]:
Business_Outcomes['Department'].value_counts()

Department
Store Operations      5400
Fresh Produce         5400
Meat/Fish & Bakery    5400
Name: count, dtype: int64

In [140]:
Business_Outcomes.groupby(['Department'])\
                    .agg(AVG_Target_Sales=('Sales_Target', 'mean'),
                         AVG_Actual_Sales=('Sales_Actual', 'mean'))\
                         .assign(
                             AVG_Gap = lambda x : x['AVG_Target_Sales'] - x['AVG_Actual_Sales'],
                             Target_status = lambda x : np.where(x['AVG_Gap'] >= 0, 'Achieved', 'Not Achieved')
                         )

,AVG_Target_Sales,AVG_Actual_Sales,AVG_Gap,Target_status
Department,,,,
Fresh Produce,63409.675000,63306.923483,102.751517,Achieved
Meat/Fish & Bakery,49318.636111,49305.090172,13.545939,Achieved
Store Operations,253638.700000,253967.042315,-328.342315,Not Achieved

In [141]:
Business_Outcomes['Year'] = Business_Outcomes['Year_Month'].str[:4]

In [142]:
Business_Outcomes.groupby(['Year','Department'])\
                    .agg(AVG_Target_Sales=('Sales_Target', 'mean'),
                         AVG_Actual_Sales=('Sales_Actual', 'mean'),
                         AVG_Waste_Percentage=('Waste_Percentage', 'mean'))\
                         .assign(
                             AVG_Gap = lambda x : x['AVG_Target_Sales'] - x['AVG_Actual_Sales'],
                             Target_status = lambda x : np.where(x['AVG_Gap'] >= 0, 'Achieved', 'Not Achieved')
                         )

                         AVG_Target_Sales  AVG_Actual_Sales  \
Year Department
2022 Fresh Produce           63409.675000      63285.286750
     Meat/Fish & Bakery      49318.636111      49238.278483
     Store Operations       253638.700000     253148.185061
2023 Fresh Produce           63409.675000      63186.260478
     Meat/Fish & Bakery      49318.636111      49226.088867
     Store Operations       253638.700000     255112.012589
2024 Fresh Produce           63409.675000      63449.223222
     Meat/Fish & Bakery      49318.636111      49450.903167
     Store Operations       253638.700000     253640.929294

                         AVG_Waste_Percentage      AVG_Gap Target_status
Year Department
2022 Fresh Produce                   3.952606   124.388250      Achieved
     Meat/Fish & Bakery              3.257056    80.357628      Achieved
     Store Operations                1.257283   490.514939      Achieved
2023 Fresh Produce                   4.028122   223.414522      Achieved
     Meat/Fish & Bakery              3.265000    92.547244      Achieved
     Store Operations                1.237267 -1473.312589  Not Achieved
2024 Fresh Produce                   3.976133   -39.548222  Not Achieved
     Meat/Fish & Bakery              3.299422  -132.267056  Not Achieved
     Store Operations                1.246939    -2.229294  Not Achieved

In [143]:
Business_Outcomes.groupby(['Year', 'Department'])\
                    .agg(AVG_Customer_Satisfaction=('Customer_Satisfaction', 'mean'),
                         AVG_NPS=('Nps_Score', 'mean'))

                         AVG_Customer_Satisfaction    AVG_NPS
Year Department
2022 Fresh Produce                        7.526389  40.507167
     Meat/Fish & Bakery                   7.516722  40.521722
     Store Operations                     7.488944  40.018556
2023 Fresh Produce                        7.501722  39.907778
     Meat/Fish & Bakery                   7.487333  39.621444
     Store Operations                     7.481667  39.581667
2024 Fresh Produce                        7.521222  40.909000
     Meat/Fish & Bakery                   7.506722  40.295500
     Store Operations                     7.471833  39.708222

In [144]:
Business_Outcomes.groupby(['Year_Month', 'Department'])\
                    .agg(AVG_Customer_Satisfaction=('Customer_Satisfaction', 'mean'),
                         AVG_NPS=('Nps_Score', 'mean'))\
                    .sort_values(['AVG_Customer_Satisfaction', 'AVG_NPS'], ascending=False).head(10)

                               AVG_Customer_Satisfaction    AVG_NPS
Year_Month Department
2022-07    Meat/Fish & Bakery                   7.698667  44.229333
2024-04    Fresh Produce                        7.668000  44.294667
2024-05    Meat/Fish & Bakery                   7.668000  43.608000
2022-09    Fresh Produce                        7.664000  44.136000
           Meat/Fish & Bakery                   7.632667  42.527333
2022-01    Store Operations                     7.632000  42.694667
2024-08    Meat/Fish & Bakery                   7.629333  42.354667
2024-04    Store Operations                     7.617333  44.091333
2023-07    Store Operations                     7.616667  43.706000
2022-02    Fresh Produce                        7.614667  40.759333

In [145]:
Business_Outcomes.groupby(['Year', 'Department'])\
                 .agg(
                     AVG_Cuatomer_Satisfaction=('Customer_Satisfaction', 'mean'),
                     AVG_On_Time_Delivery=('On_Time_Delivery', 'mean')
                     )

                         AVG_Cuatomer_Satisfaction  AVG_On_Time_Delivery
Year Department
2022 Fresh Produce                        7.526389             93.952944
     Meat/Fish & Bakery                   7.516722             94.029333
     Store Operations                     7.488944             94.018833
2023 Fresh Produce                        7.501722             93.911000
     Meat/Fish & Bakery                   7.487333             93.999889
     Store Operations                     7.481667             93.954056
2024 Fresh Produce                        7.521222             94.018667
     Meat/Fish & Bakery                   7.506722             93.894167
     Store Operations                     7.471833             94.040889

In [146]:
sheets.keys()

dict_keys(['employees', 'stores', 'monthly_performance', 'role_kpis', 'business_outcomes', 'Data_Dictionary'])

In [147]:
Tables_names = ['Employees', 'Stores', 'Monthly_performance', 'Role_KPIs', 'Business_Outcomes']
Tables = [Employees, Stores, Monthly_performance, Role_KPIs, Business_Outcomes]

for name, df in zip(Tables_names, Tables):
    print("-" * 30)
    print(f"📊 DATA AUDIT FOR: {name}")
    print("-" * 30)
    
    print(f"Missing Values Checking :\n{df.isna().sum()}\n")
    
    print(f"Summary Statistics :\n{df.describe()}\n")
    print("\n")

------------------------------
📊 DATA AUDIT FOR: Employees
------------------------------
Missing Values Checking :
Employee_Id                    0
Full_Name                      0
Age                            0
Education_Level                0
Hire_Date                      0
Exit_Date                   6009
Department                     0
Job_Role                       0
Job_Level                      0
Employment_Type                0
Base_Salary_Annual             0
Store_Location                 0
Store_Location_Latitude        0
Store_Location_Longitude       0
Store_Id                       0
Manager_Id                     5
Manager_Name                   5
Manager_Status                 5
Base_Salary_Monthly            0
Age Group                      0
dtype: int64

Summary Statistics :
               Age                   Hire_Date                   Exit_Date  \
count  7500.000000                        7500                        1491
mean     32.450000  2019-10-29 00:05:45.600000  2022-08-22 09:05:40.442656
min      21.000000         2012-01-04 00:00:00         2012-04-30 00:00:00
25%      27.000000         2018-12-19 00:00:00         2021-10-27 12:00:00
50%      32.000000         2020-06-26 00:00:00         2022-12-12 00:00:00
75%      37.000000         2021-05-13 00:00:00         2023-12-17 12:00:00
max      64.000000         2022-01-01 00:00:00         2024-12-29 00:00:00
std       7.482319                         NaN                         NaN

       Base_Salary_Annual  Store_Location_Latitude  Store_Location_Longitude  \
count         7500.000000              7500.000000               7500.000000
mean         27253.855732                36.954572                -96.160918
min           8823.460000                29.424100               -122.678400
25%          19899.520000                32.776700               -112.074000
50%          27394.165000                36.169900                -95.369800
75%          31945.697500                39.961200                -82.998800
max         177873.610000                47.606200                -71.058900
std          10217.242704                 4.878566                 16.457037

       Base_Salary_Monthly
count          7500.000000
mean           2271.154644
min             735.288333
25%            1658.293333
50%            2282.847083
75%            2662.141458
max           14822.800833
std             851.436892



------------------------------
📊 DATA AUDIT FOR: Stores
------------------------------
Missing Values Checking :
Store_Id          0
Store_Name        0
City              0
City_Latitude     0
City_Longitude    0
Store_Type        0
Opening_Date      0
dtype: int64

Summary Statistics :
       City_Latitude  City_Longitude         Opening_Date
count     150.000000      150.000000                  150
mean       37.069471      -94.894056  2019-12-29 06:33:36
min        29.424100     -122.678400  2015-08-20 00:00:00
25%        32.776700     -104.990300  2017-09-06 18:00:00
50%        36.754050      -90.049000  2020-02-27 00:00:00
75%        40.712800      -82.998800  2022-03-13 18:00:00
max        47.606200      -71.058900  2024-08-09 00:00:00
std         5.022388       15.982066                  NaN



------------------------------
📊 DATA AUDIT FOR: Monthly_performance
------------------------------
Missing Values Checking :
Employee_Id              0
Year_Month               0
Performance_Rating       0
Training_Hours           0
Overtime_Hours           0
Absenteeism_Days         0
Promotion_Flag           0
Salary_Increase_Flag     0
Monthly_Bonus            0
Benefits_Cost            0
Employee_Satisfaction    0
Engagement_Index         0
Manager_Evaluation       0
Year                     0
dtype: int64

Summary Statistics :
       Performance_Rating  Training_Hours  Overtime_Hours  Absenteeism_Days  \
count       236591.000000   236591.000000   236591.000000     236591.000000
mean             3.701753        2.807681        8.031658          0.711637
std              0.442421        2.273293        4.981170          0.861559
min              1.000000        0.000000        0.000000          0.000000
25%              3.400000        1.000000        4.000000          0.000000
50%              3.720000        2.000000        8.000000          1.000000
75%              4.020000        4.000000       11.000000          1.000000
max              5.000000       27.000000       39.000000          7.000000

       Monthly_Bonus  Benefits_Cost  Employee_Satisfaction  Engagement_Index  \
count  236591.000000  236591.000000          236591.000000     236591.000000
mean      248.604603     748.917364               7.238340          7.220323
std       302.626752     458.760361               1.292169          1.485795
min        10.370000      41.740000               1.000000          1.000000
25%        65.110000     410.640000               6.400000          6.200000
50%       124.530000     692.820000               7.200000          7.200000
75%       314.770000     970.720000               8.100000          8.300000
max      3762.520000    3112.500000              10.000000         10.000000

       Manager_Evaluation
count       236591.000000
mean             3.700053
std              0.533884
min              1.000000
25%              3.300000
50%              3.700000
75%              4.100000
max              5.000000



------------------------------
📊 DATA AUDIT FOR: Role_KPIs
------------------------------
Missing Values Checking :
Employee_Id           0
Year_Month            0
Kpi_1_Value           0
Kpi_1_Name            0
Kpi_2_Value           0
Kpi_2_Name            0
Kpi_3_Value           0
Kpi_3_Name            0
Productivity_Index    0
Year                  0
dtype: int64

Summary Statistics :
         Kpi_1_Value    Kpi_2_Value    Kpi_3_Value  Productivity_Index
count  236591.000000  236591.000000  236591.000000       236591.000000
mean      143.986892      20.165928      21.092766            1.350878
std       226.427191      29.638375      78.520609            0.221203
min         0.500000       0.000000       0.000000            0.000000
25%        78.920000       6.670000       4.460000            1.202000
50%        86.840000       7.730000       6.470000            1.361000
75%        95.700000       9.690000       7.710000            1.509000
max      1400.000000     100.000000     650.000000            2.000000



------------------------------
📊 DATA AUDIT FOR: Business_Outcomes
------------------------------
Missing Values Checking :
Store_Id                 0
Department               0
Year_Month               0
Sales_Target             0
Sales_Actual             0
Customer_Satisfaction    0
Nps_Score                0
Waste_Percentage         0
On_Time_Delivery         0
Year                     0
dtype: int64

Summary Statistics :
        Sales_Target   Sales_Actual  Customer_Satisfaction     Nps_Score  \
count   16200.000000   16200.000000           16200.000000  16200.000000
mean   122122.337037  122193.018657               7.500284     40.119006
std    111447.195395  114597.712846               0.988154     24.723058
min     17850.000000   11148.860000               3.500000    -56.500000
25%     45500.000000   43763.495000               6.800000     23.200000
50%     69300.000000   70502.905000               7.500000     40.400000
75%    180000.000000  171523.280000               8.200000     57.000000
max    589680.000000  746030.660000              10.000000    100.000000

       Waste_Percentage  On_Time_Delivery
count      16200.000000      16200.000000
mean           2.835536         93.979975
std            1.482315          2.945439
min            0.500000         80.600000
25%            1.580000         92.000000
50%            2.680000         94.000000
75%            4.072500         96.000000
max            6.000000        100.000000